Teamspeak3:
        restart: always
        image: asos/teamspeak:1.0.0.5
        container_name: teamspeak
        ports:
            - "${HOST_VOICE_PORT}:9987/udp"
            - "${HOST_QUERY_PORT}:10011"
            - "${HOST_FILE_TRANSFER_PORT}:30033"
        volumes:
            - ${DATA_VOLUME}:/teamspeak/files

        environment:
            - TS3_MARIADB_HOST=${MDB_HOST}
            - TS3_MADIADB_PORT=${MDB_PORT}
            - TS3_MARIDDB_USER=${MDB_USER}
            - TS3_MARIDDB_PASS=${MDB_PASS}
            - TS3_MARIDDB_DB=${MDB_DB}
            - TS3_LICENSE_PATH=${TS3_LICENSE_PATH}
