Teamspeak:
        restart: always
        image: asos/teamspeak:latest
        container_name: teamspeak_latest
        ports:
            - "9987:9987/udp"
            - "10011:10011"
            - "30033:30033"
        volumes:
            - /storage/teamspeak:/data