Teamspeak3:
        restart: always
        image: asos/teamspeak:2.1.0.1
        container_name: teamspeak
        ports:
            - "${HOST_VOICE_PORT}:9987/udp"
            - "${HOST_QUERY_PORT}:10011"
            - "${HOST_FILE_TRANSFER_PORT}:30033"
        volumes:
            - ${DATA_VOLUME}:/teamspeak/files

        environment:
            - TS3_MARIADB_HOST=${TS3_MARIADB_HOST}
            - TS3_MADIADB_PORT=${TS3_MARIADB_PORT}
            - TS3_MARIDDB_USER=${TS3_MARIADB_USER}
            - TS3_MARIDDB_PASS=${TS3_MARIADB_PASS}
            - TS3_MARIDDB_DB=${TS3_MARIADB_DB}
            - TS3_LICENSE_PATH=${TS3_MARIADB_LICENSE_PATH}
